name: Deploy

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches:
      - main

permissions:
  contents: read
  packages: write

concurrency:
  group: production-deploy
  cancel-in-progress: true

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io \
            -u "${{ github.actor }}" \
            --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/nelisiwe04/tender-scrapping:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/nelisiwe04/tender-scrapping:latest

      - name: Deploy
        run: |
          docker pull ghcr.io/nelisiwe04/tender-scrapping:latest
          docker compose up -d
